{{- if .Values.eventIngestor.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "analytics-service.fullname" . }}-{{ .Values.eventIngestor.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "analytics-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.eventIngestor.name }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.eventIngestor.autoscaling.enabled }}
  replicas: {{ .Values.eventIngestor.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "analytics-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.eventIngestor.name }}
  template:
    metadata:
      labels:
        {{- include "analytics-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.eventIngestor.name }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "analytics-service.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "analytics-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.eventIngestor.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.eventIngestor.image.repository }}:{{ .Values.eventIngestor.image.tag }}"
          imagePullPolicy: {{ .Values.eventIngestor.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.eventIngestor.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.eventIngestor.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.eventIngestor.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.eventIngestor.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.eventIngestor.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.eventIngestor.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.eventIngestor.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.eventIngestor.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.eventIngestor.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.eventIngestor.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.eventIngestor.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.eventIngestor.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "analytics-service.configMapName" . }}
            {{- with .Values.eventIngestor.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.eventIngestor.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

{{- if .Values.attributionEngine.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "analytics-service.fullname" . }}-{{ .Values.attributionEngine.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "analytics-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.attributionEngine.name }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.attributionEngine.autoscaling.enabled }}
  replicas: {{ .Values.attributionEngine.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "analytics-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.attributionEngine.name }}
  template:
    metadata:
      labels:
        {{- include "analytics-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.attributionEngine.name }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "analytics-service.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "analytics-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.attributionEngine.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.attributionEngine.image.repository }}:{{ .Values.attributionEngine.image.tag }}"
          imagePullPolicy: {{ .Values.attributionEngine.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.attributionEngine.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.attributionEngine.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.attributionEngine.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.attributionEngine.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.attributionEngine.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.attributionEngine.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.attributionEngine.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.attributionEngine.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.attributionEngine.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.attributionEngine.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.attributionEngine.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.attributionEngine.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "analytics-service.configMapName" . }}
            {{- with .Values.attributionEngine.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.attributionEngine.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

{{- if .Values.analyticsApi.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "analytics-service.fullname" . }}-{{ .Values.analyticsApi.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "analytics-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.analyticsApi.name }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.analyticsApi.autoscaling.enabled }}
  replicas: {{ .Values.analyticsApi.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "analytics-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.analyticsApi.name }}
  template:
    metadata:
      labels:
        {{- include "analytics-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.analyticsApi.name }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "analytics-service.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "analytics-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.analyticsApi.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.analyticsApi.image.repository }}:{{ .Values.analyticsApi.image.tag }}"
          imagePullPolicy: {{ .Values.analyticsApi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.analyticsApi.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.analyticsApi.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.analyticsApi.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.analyticsApi.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.analyticsApi.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.analyticsApi.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.analyticsApi.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.analyticsApi.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.analyticsApi.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.analyticsApi.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.analyticsApi.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.analyticsApi.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "analytics-service.configMapName" . }}
            {{- with .Values.analyticsApi.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.analyticsApi.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

{{- if .Values.metricsAggregator.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "analytics-service.fullname" . }}-{{ .Values.metricsAggregator.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "analytics-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.metricsAggregator.name }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.metricsAggregator.autoscaling.enabled }}
  replicas: {{ .Values.metricsAggregator.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "analytics-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.metricsAggregator.name }}
  template:
    metadata:
      labels:
        {{- include "analytics-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.metricsAggregator.name }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "analytics-service.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "analytics-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.metricsAggregator.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.metricsAggregator.image.repository }}:{{ .Values.metricsAggregator.image.tag }}"
          imagePullPolicy: {{ .Values.metricsAggregator.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.metricsAggregator.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.metricsAggregator.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.metricsAggregator.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.metricsAggregator.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.metricsAggregator.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.metricsAggregator.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.metricsAggregator.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.metricsAggregator.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.metricsAggregator.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.metricsAggregator.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.metricsAggregator.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.metricsAggregator.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "analytics-service.configMapName" . }}
            {{- with .Values.metricsAggregator.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.metricsAggregator.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
