{{- if .Values.eventIngestor.enabled }}
{{- if .Values.eventIngestor.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "analytics-service.fullname" . }}-{{ .Values.eventIngestor.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "analytics-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.eventIngestor.name }}
spec:
  {{- if .Values.eventIngestor.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.eventIngestor.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.eventIngestor.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.eventIngestor.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "analytics-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.eventIngestor.name }}
{{- end }}
{{- end }}

{{- if .Values.attributionEngine.enabled }}
{{- if .Values.attributionEngine.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "analytics-service.fullname" . }}-{{ .Values.attributionEngine.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "analytics-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.attributionEngine.name }}
spec:
  {{- if .Values.attributionEngine.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.attributionEngine.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.attributionEngine.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.attributionEngine.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "analytics-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.attributionEngine.name }}
{{- end }}
{{- end }}

{{- if .Values.analyticsApi.enabled }}
{{- if .Values.analyticsApi.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "analytics-service.fullname" . }}-{{ .Values.analyticsApi.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "analytics-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.analyticsApi.name }}
spec:
  {{- if .Values.analyticsApi.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.analyticsApi.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.analyticsApi.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.analyticsApi.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "analytics-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.analyticsApi.name }}
{{- end }}
{{- end }}

{{- if .Values.metricsAggregator.enabled }}
{{- if .Values.metricsAggregator.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "analytics-service.fullname" . }}-{{ .Values.metricsAggregator.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "analytics-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.metricsAggregator.name }}
spec:
  {{- if .Values.metricsAggregator.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.metricsAggregator.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.metricsAggregator.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.metricsAggregator.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "analytics-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.metricsAggregator.name }}
{{- end }}
{{- end }}
