{{- if .Values.experimentEngine.enabled }}
{{- if .Values.experimentEngine.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "experimentation-service.fullname" . }}-{{ .Values.experimentEngine.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "experimentation-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.experimentEngine.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "experimentation-service.fullname" . }}-{{ .Values.experimentEngine.name }}
  minReplicas: {{ .Values.experimentEngine.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.experimentEngine.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.experimentEngine.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.experimentEngine.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.experimentEngine.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.experimentEngine.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}

{{- if .Values.featureFlagService.enabled }}
{{- if .Values.featureFlagService.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "experimentation-service.fullname" . }}-{{ .Values.featureFlagService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "experimentation-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.featureFlagService.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "experimentation-service.fullname" . }}-{{ .Values.featureFlagService.name }}
  minReplicas: {{ .Values.featureFlagService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.featureFlagService.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.featureFlagService.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.featureFlagService.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.featureFlagService.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.featureFlagService.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}

{{- if .Values.abTestAnalyzer.enabled }}
{{- if .Values.abTestAnalyzer.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "experimentation-service.fullname" . }}-{{ .Values.abTestAnalyzer.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "experimentation-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.abTestAnalyzer.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "experimentation-service.fullname" . }}-{{ .Values.abTestAnalyzer.name }}
  minReplicas: {{ .Values.abTestAnalyzer.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.abTestAnalyzer.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.abTestAnalyzer.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.abTestAnalyzer.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.abTestAnalyzer.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.abTestAnalyzer.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
