{{- if .Values.experimentEngine.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "experimentation-service.fullname" . }}-{{ .Values.experimentEngine.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "experimentation-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.experimentEngine.name }}
spec:
  type: {{ .Values.experimentEngine.service.type }}
  ports:
    - port: {{ .Values.experimentEngine.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "experimentation-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.experimentEngine.name }}
{{- end }}

{{- if .Values.featureFlagService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "experimentation-service.fullname" . }}-{{ .Values.featureFlagService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "experimentation-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.featureFlagService.name }}
spec:
  type: {{ .Values.featureFlagService.service.type }}
  ports:
    - port: {{ .Values.featureFlagService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "experimentation-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.featureFlagService.name }}
{{- end }}

{{- if .Values.abTestAnalyzer.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "experimentation-service.fullname" . }}-{{ .Values.abTestAnalyzer.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "experimentation-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.abTestAnalyzer.name }}
spec:
  type: {{ .Values.abTestAnalyzer.service.type }}
  ports:
    - port: {{ .Values.abTestAnalyzer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "experimentation-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.abTestAnalyzer.name }}
{{- end }}
