{{- if .Values.contentApi.enabled }}
{{- if .Values.contentApi.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "content-service.fullname" . }}-{{ .Values.contentApi.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "content-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.contentApi.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "content-service.fullname" . }}-{{ .Values.contentApi.name }}
  minReplicas: {{ .Values.contentApi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.contentApi.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.contentApi.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.contentApi.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.contentApi.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.contentApi.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}

{{- if .Values.contentRenderer.enabled }}
{{- if .Values.contentRenderer.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "content-service.fullname" . }}-{{ .Values.contentRenderer.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "content-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.contentRenderer.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "content-service.fullname" . }}-{{ .Values.contentRenderer.name }}
  minReplicas: {{ .Values.contentRenderer.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.contentRenderer.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.contentRenderer.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.contentRenderer.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.contentRenderer.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.contentRenderer.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}

{{- if .Values.contentScheduler.enabled }}
{{- if .Values.contentScheduler.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "content-service.fullname" . }}-{{ .Values.contentScheduler.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "content-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.contentScheduler.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "content-service.fullname" . }}-{{ .Values.contentScheduler.name }}
  minReplicas: {{ .Values.contentScheduler.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.contentScheduler.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.contentScheduler.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.contentScheduler.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.contentScheduler.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.contentScheduler.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}

{{- if .Values.searchIndexer.enabled }}
{{- if .Values.searchIndexer.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "content-service.fullname" . }}-{{ .Values.searchIndexer.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "content-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.searchIndexer.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "content-service.fullname" . }}-{{ .Values.searchIndexer.name }}
  minReplicas: {{ .Values.searchIndexer.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.searchIndexer.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.searchIndexer.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.searchIndexer.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.searchIndexer.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.searchIndexer.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
