{{- if .Values.contentApi.enabled }}
{{- if .Values.contentApi.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "content-service.fullname" . }}-{{ .Values.contentApi.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "content-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.contentApi.name }}
spec:
  {{- if .Values.contentApi.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.contentApi.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.contentApi.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.contentApi.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "content-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.contentApi.name }}
{{- end }}
{{- end }}

{{- if .Values.contentRenderer.enabled }}
{{- if .Values.contentRenderer.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "content-service.fullname" . }}-{{ .Values.contentRenderer.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "content-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.contentRenderer.name }}
spec:
  {{- if .Values.contentRenderer.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.contentRenderer.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.contentRenderer.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.contentRenderer.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "content-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.contentRenderer.name }}
{{- end }}
{{- end }}

{{- if .Values.contentScheduler.enabled }}
{{- if .Values.contentScheduler.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "content-service.fullname" . }}-{{ .Values.contentScheduler.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "content-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.contentScheduler.name }}
spec:
  {{- if .Values.contentScheduler.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.contentScheduler.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.contentScheduler.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.contentScheduler.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "content-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.contentScheduler.name }}
{{- end }}
{{- end }}

{{- if .Values.searchIndexer.enabled }}
{{- if .Values.searchIndexer.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "content-service.fullname" . }}-{{ .Values.searchIndexer.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "content-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.searchIndexer.name }}
spec:
  {{- if .Values.searchIndexer.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.searchIndexer.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.searchIndexer.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.searchIndexer.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "content-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.searchIndexer.name }}
{{- end }}
{{- end }}
