apiVersion: v1
kind: Namespace
metadata:
  name: broxiva-production
  labels:
    name: broxiva-production
    environment: production
    app: broxiva
    managed-by: kustomize
  annotations:
    description: "Broxiva production environment"
    contact: "devops@broxiva.com"
    incident-email: "incidents@broxiva.com"
