apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: broxiva

resources:
  - namespace.yaml

commonLabels:
  app.kubernetes.io/part-of: broxiva-platform
  app.kubernetes.io/managed-by: kustomize

configMapGenerator:
  - name: broxiva-config
    literals:
      - APP_ENV=production
      - LOG_LEVEL=info
      - ENABLE_AI_SERVICES=true
