apiVersion: v1
kind: Namespace
metadata:
  name: broxiva
  labels:
    app.kubernetes.io/name: broxiva
    app.kubernetes.io/managed-by: kustomize
---
apiVersion: v1
kind: Namespace
metadata:
  name: broxiva-ai
  labels:
    app.kubernetes.io/name: broxiva-ai
    app.kubernetes.io/managed-by: kustomize
---
apiVersion: v1
kind: Namespace
metadata:
  name: broxiva-monitoring
  labels:
    app.kubernetes.io/name: broxiva-monitoring
    app.kubernetes.io/managed-by: kustomize
