{{- if .Values.sitemapGenerator.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "seo-service.fullname" . }}-{{ .Values.sitemapGenerator.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seo-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.sitemapGenerator.name }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.sitemapGenerator.autoscaling.enabled }}
  replicas: {{ .Values.sitemapGenerator.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "seo-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.sitemapGenerator.name }}
  template:
    metadata:
      labels:
        {{- include "seo-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.sitemapGenerator.name }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "seo-service.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "seo-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.sitemapGenerator.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.sitemapGenerator.image.repository }}:{{ .Values.sitemapGenerator.image.tag }}"
          imagePullPolicy: {{ .Values.sitemapGenerator.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.sitemapGenerator.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.sitemapGenerator.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.sitemapGenerator.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.sitemapGenerator.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.sitemapGenerator.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.sitemapGenerator.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.sitemapGenerator.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.sitemapGenerator.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.sitemapGenerator.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.sitemapGenerator.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.sitemapGenerator.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.sitemapGenerator.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "seo-service.configMapName" . }}
            {{- with .Values.sitemapGenerator.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.sitemapGenerator.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

{{- if .Values.robotsTxtServer.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "seo-service.fullname" . }}-{{ .Values.robotsTxtServer.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seo-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.robotsTxtServer.name }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.robotsTxtServer.autoscaling.enabled }}
  replicas: {{ .Values.robotsTxtServer.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "seo-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.robotsTxtServer.name }}
  template:
    metadata:
      labels:
        {{- include "seo-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.robotsTxtServer.name }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "seo-service.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "seo-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.robotsTxtServer.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.robotsTxtServer.image.repository }}:{{ .Values.robotsTxtServer.image.tag }}"
          imagePullPolicy: {{ .Values.robotsTxtServer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.robotsTxtServer.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.robotsTxtServer.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.robotsTxtServer.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.robotsTxtServer.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.robotsTxtServer.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.robotsTxtServer.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.robotsTxtServer.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.robotsTxtServer.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.robotsTxtServer.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.robotsTxtServer.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.robotsTxtServer.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.robotsTxtServer.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "seo-service.configMapName" . }}
            {{- with .Values.robotsTxtServer.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.robotsTxtServer.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

{{- if .Values.schemaOrgGenerator.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "seo-service.fullname" . }}-{{ .Values.schemaOrgGenerator.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seo-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.schemaOrgGenerator.name }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.schemaOrgGenerator.autoscaling.enabled }}
  replicas: {{ .Values.schemaOrgGenerator.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "seo-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.schemaOrgGenerator.name }}
  template:
    metadata:
      labels:
        {{- include "seo-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.schemaOrgGenerator.name }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "seo-service.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "seo-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.schemaOrgGenerator.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.schemaOrgGenerator.image.repository }}:{{ .Values.schemaOrgGenerator.image.tag }}"
          imagePullPolicy: {{ .Values.schemaOrgGenerator.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.schemaOrgGenerator.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.schemaOrgGenerator.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.schemaOrgGenerator.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.schemaOrgGenerator.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.schemaOrgGenerator.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.schemaOrgGenerator.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.schemaOrgGenerator.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.schemaOrgGenerator.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.schemaOrgGenerator.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.schemaOrgGenerator.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.schemaOrgGenerator.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.schemaOrgGenerator.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "seo-service.configMapName" . }}
            {{- with .Values.schemaOrgGenerator.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.schemaOrgGenerator.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

{{- if .Values.seoAuditor.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "seo-service.fullname" . }}-{{ .Values.seoAuditor.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seo-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.seoAuditor.name }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.seoAuditor.autoscaling.enabled }}
  replicas: {{ .Values.seoAuditor.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "seo-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.seoAuditor.name }}
  template:
    metadata:
      labels:
        {{- include "seo-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.seoAuditor.name }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "seo-service.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "seo-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.seoAuditor.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.seoAuditor.image.repository }}:{{ .Values.seoAuditor.image.tag }}"
          imagePullPolicy: {{ .Values.seoAuditor.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.seoAuditor.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.seoAuditor.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.seoAuditor.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.seoAuditor.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.seoAuditor.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.seoAuditor.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.seoAuditor.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.seoAuditor.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.seoAuditor.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.seoAuditor.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.seoAuditor.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.seoAuditor.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "seo-service.configMapName" . }}
            {{- with .Values.seoAuditor.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.seoAuditor.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

{{- if .Values.coreWebVitalsTracker.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "seo-service.fullname" . }}-{{ .Values.coreWebVitalsTracker.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seo-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.coreWebVitalsTracker.name }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.coreWebVitalsTracker.autoscaling.enabled }}
  replicas: {{ .Values.coreWebVitalsTracker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "seo-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.coreWebVitalsTracker.name }}
  template:
    metadata:
      labels:
        {{- include "seo-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.coreWebVitalsTracker.name }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "seo-service.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "seo-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.coreWebVitalsTracker.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.coreWebVitalsTracker.image.repository }}:{{ .Values.coreWebVitalsTracker.image.tag }}"
          imagePullPolicy: {{ .Values.coreWebVitalsTracker.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.coreWebVitalsTracker.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.coreWebVitalsTracker.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.coreWebVitalsTracker.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.coreWebVitalsTracker.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.coreWebVitalsTracker.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.coreWebVitalsTracker.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.coreWebVitalsTracker.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.coreWebVitalsTracker.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.coreWebVitalsTracker.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.coreWebVitalsTracker.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.coreWebVitalsTracker.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.coreWebVitalsTracker.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "seo-service.configMapName" . }}
            {{- with .Values.coreWebVitalsTracker.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.coreWebVitalsTracker.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
