{{- if .Values.sitemapGenerator.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seo-service.fullname" . }}-{{ .Values.sitemapGenerator.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seo-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.sitemapGenerator.name }}
spec:
  type: {{ .Values.sitemapGenerator.service.type }}
  ports:
    - port: {{ .Values.sitemapGenerator.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "seo-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.sitemapGenerator.name }}
{{- end }}

{{- if .Values.robotsTxtServer.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seo-service.fullname" . }}-{{ .Values.robotsTxtServer.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seo-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.robotsTxtServer.name }}
spec:
  type: {{ .Values.robotsTxtServer.service.type }}
  ports:
    - port: {{ .Values.robotsTxtServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "seo-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.robotsTxtServer.name }}
{{- end }}

{{- if .Values.schemaOrgGenerator.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seo-service.fullname" . }}-{{ .Values.schemaOrgGenerator.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seo-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.schemaOrgGenerator.name }}
spec:
  type: {{ .Values.schemaOrgGenerator.service.type }}
  ports:
    - port: {{ .Values.schemaOrgGenerator.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "seo-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.schemaOrgGenerator.name }}
{{- end }}

{{- if .Values.seoAuditor.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seo-service.fullname" . }}-{{ .Values.seoAuditor.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seo-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.seoAuditor.name }}
spec:
  type: {{ .Values.seoAuditor.service.type }}
  ports:
    - port: {{ .Values.seoAuditor.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "seo-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.seoAuditor.name }}
{{- end }}

{{- if .Values.coreWebVitalsTracker.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seo-service.fullname" . }}-{{ .Values.coreWebVitalsTracker.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seo-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.coreWebVitalsTracker.name }}
spec:
  type: {{ .Values.coreWebVitalsTracker.service.type }}
  ports:
    - port: {{ .Values.coreWebVitalsTracker.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "seo-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.coreWebVitalsTracker.name }}
{{- end }}
