{{- if .Values.emailDispatcher.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lifecycle-service.fullname" . }}-{{ .Values.emailDispatcher.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lifecycle-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.emailDispatcher.name }}
spec:
  type: {{ .Values.emailDispatcher.service.type }}
  ports:
    - port: {{ .Values.emailDispatcher.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lifecycle-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.emailDispatcher.name }}
{{- end }}

{{- if .Values.lifecycleOrchestrator.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lifecycle-service.fullname" . }}-{{ .Values.lifecycleOrchestrator.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lifecycle-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.lifecycleOrchestrator.name }}
spec:
  type: {{ .Values.lifecycleOrchestrator.service.type }}
  ports:
    - port: {{ .Values.lifecycleOrchestrator.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lifecycle-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.lifecycleOrchestrator.name }}
{{- end }}

{{- if .Values.triggerProcessor.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lifecycle-service.fullname" . }}-{{ .Values.triggerProcessor.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lifecycle-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.triggerProcessor.name }}
spec:
  type: {{ .Values.triggerProcessor.service.type }}
  ports:
    - port: {{ .Values.triggerProcessor.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lifecycle-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.triggerProcessor.name }}
{{- end }}

{{- if .Values.templateRenderer.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lifecycle-service.fullname" . }}-{{ .Values.templateRenderer.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lifecycle-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.templateRenderer.name }}
spec:
  type: {{ .Values.templateRenderer.service.type }}
  ports:
    - port: {{ .Values.templateRenderer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lifecycle-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.templateRenderer.name }}
{{- end }}
