{{- if .Values.userProfiler.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "personalization-service.fullname" . }}-{{ .Values.userProfiler.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "personalization-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.userProfiler.name }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.userProfiler.autoscaling.enabled }}
  replicas: {{ .Values.userProfiler.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "personalization-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.userProfiler.name }}
  template:
    metadata:
      labels:
        {{- include "personalization-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.userProfiler.name }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "personalization-service.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "personalization-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.userProfiler.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.userProfiler.image.repository }}:{{ .Values.userProfiler.image.tag }}"
          imagePullPolicy: {{ .Values.userProfiler.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.userProfiler.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.userProfiler.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.userProfiler.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.userProfiler.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.userProfiler.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.userProfiler.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.userProfiler.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.userProfiler.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.userProfiler.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.userProfiler.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.userProfiler.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.userProfiler.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "personalization-service.configMapName" . }}
            {{- with .Values.userProfiler.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.userProfiler.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

{{- if .Values.recommendationEngine.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "personalization-service.fullname" . }}-{{ .Values.recommendationEngine.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "personalization-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.recommendationEngine.name }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.recommendationEngine.autoscaling.enabled }}
  replicas: {{ .Values.recommendationEngine.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "personalization-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.recommendationEngine.name }}
  template:
    metadata:
      labels:
        {{- include "personalization-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.recommendationEngine.name }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "personalization-service.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "personalization-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.recommendationEngine.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.recommendationEngine.image.repository }}:{{ .Values.recommendationEngine.image.tag }}"
          imagePullPolicy: {{ .Values.recommendationEngine.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.recommendationEngine.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.recommendationEngine.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.recommendationEngine.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.recommendationEngine.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.recommendationEngine.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.recommendationEngine.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.recommendationEngine.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.recommendationEngine.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.recommendationEngine.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.recommendationEngine.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.recommendationEngine.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.recommendationEngine.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "personalization-service.configMapName" . }}
            {{- with .Values.recommendationEngine.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.recommendationEngine.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

{{- if .Values.personalizationApi.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "personalization-service.fullname" . }}-{{ .Values.personalizationApi.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "personalization-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.personalizationApi.name }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.personalizationApi.autoscaling.enabled }}
  replicas: {{ .Values.personalizationApi.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "personalization-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.personalizationApi.name }}
  template:
    metadata:
      labels:
        {{- include "personalization-service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.personalizationApi.name }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- include "personalization-service.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "personalization-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.personalizationApi.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.personalizationApi.image.repository }}:{{ .Values.personalizationApi.image.tag }}"
          imagePullPolicy: {{ .Values.personalizationApi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.personalizationApi.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.personalizationApi.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.personalizationApi.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.personalizationApi.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.personalizationApi.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.personalizationApi.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.personalizationApi.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.personalizationApi.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.personalizationApi.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.personalizationApi.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.personalizationApi.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.personalizationApi.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "personalization-service.configMapName" . }}
            {{- with .Values.personalizationApi.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.personalizationApi.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
