{{- if .Values.userProfiler.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "personalization-service.fullname" . }}-{{ .Values.userProfiler.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "personalization-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.userProfiler.name }}
spec:
  type: {{ .Values.userProfiler.service.type }}
  ports:
    - port: {{ .Values.userProfiler.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "personalization-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.userProfiler.name }}
{{- end }}

{{- if .Values.recommendationEngine.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "personalization-service.fullname" . }}-{{ .Values.recommendationEngine.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "personalization-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.recommendationEngine.name }}
spec:
  type: {{ .Values.recommendationEngine.service.type }}
  ports:
    - port: {{ .Values.recommendationEngine.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "personalization-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.recommendationEngine.name }}
{{- end }}

{{- if .Values.personalizationApi.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "personalization-service.fullname" . }}-{{ .Values.personalizationApi.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "personalization-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.personalizationApi.name }}
spec:
  type: {{ .Values.personalizationApi.service.type }}
  ports:
    - port: {{ .Values.personalizationApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "personalization-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.personalizationApi.name }}
{{- end }}
