{{- if .Values.growthApi.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "growth-service.fullname" . }}-{{ .Values.growthApi.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "growth-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.growthApi.name }}
spec:
  type: {{ .Values.growthApi.service.type }}
  ports:
    - port: {{ .Values.growthApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "growth-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.growthApi.name }}
{{- end }}

{{- if .Values.referralEngine.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "growth-service.fullname" . }}-{{ .Values.referralEngine.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "growth-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.referralEngine.name }}
spec:
  type: {{ .Values.referralEngine.service.type }}
  ports:
    - port: {{ .Values.referralEngine.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "growth-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.referralEngine.name }}
{{- end }}

{{- if .Values.affiliateTracker.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "growth-service.fullname" . }}-{{ .Values.affiliateTracker.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "growth-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.affiliateTracker.name }}
spec:
  type: {{ .Values.affiliateTracker.service.type }}
  ports:
    - port: {{ .Values.affiliateTracker.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "growth-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.affiliateTracker.name }}
{{- end }}

{{- if .Values.landingBuilder.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "growth-service.fullname" . }}-{{ .Values.landingBuilder.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "growth-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.landingBuilder.name }}
spec:
  type: {{ .Values.landingBuilder.service.type }}
  ports:
    - port: {{ .Values.landingBuilder.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "growth-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.landingBuilder.name }}
{{- end }}
