apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-marketing-service.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-marketing-service.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
