{{- if .Values.emailDispatcher.enabled }}
{{- if .Values.emailDispatcher.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "lifecycle-service.fullname" . }}-{{ .Values.emailDispatcher.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lifecycle-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.emailDispatcher.name }}
spec:
  {{- if .Values.emailDispatcher.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.emailDispatcher.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lifecycle-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.emailDispatcher.name }}
{{- end }}
{{- end }}

{{- if .Values.lifecycleOrchestrator.enabled }}
{{- if .Values.lifecycleOrchestrator.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "lifecycle-service.fullname" . }}-{{ .Values.lifecycleOrchestrator.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lifecycle-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.lifecycleOrchestrator.name }}
spec:
  {{- if .Values.lifecycleOrchestrator.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.lifecycleOrchestrator.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lifecycle-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.lifecycleOrchestrator.name }}
{{- end }}
{{- end }}

{{- if .Values.triggerProcessor.enabled }}
{{- if .Values.triggerProcessor.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "lifecycle-service.fullname" . }}-{{ .Values.triggerProcessor.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lifecycle-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.triggerProcessor.name }}
spec:
  {{- if .Values.triggerProcessor.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.triggerProcessor.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lifecycle-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.triggerProcessor.name }}
{{- end }}
{{- end }}

{{- if .Values.templateRenderer.enabled }}
{{- if .Values.templateRenderer.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "lifecycle-service.fullname" . }}-{{ .Values.templateRenderer.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lifecycle-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.templateRenderer.name }}
spec:
  {{- if .Values.templateRenderer.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.templateRenderer.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lifecycle-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.templateRenderer.name }}
{{- end }}
{{- end }}
