{{- if .Values.promoEngine.enabled }}
{{- if .Values.promoEngine.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "commerce-service.fullname" . }}-{{ .Values.promoEngine.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "commerce-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.promoEngine.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "commerce-service.fullname" . }}-{{ .Values.promoEngine.name }}
  minReplicas: {{ .Values.promoEngine.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.promoEngine.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.promoEngine.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.promoEngine.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
{{- end }}

{{- if .Values.inAppMessaging.enabled }}
{{- if .Values.inAppMessaging.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "commerce-service.fullname" . }}-{{ .Values.inAppMessaging.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "commerce-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.inAppMessaging.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "commerce-service.fullname" . }}-{{ .Values.inAppMessaging.name }}
  minReplicas: {{ .Values.inAppMessaging.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.inAppMessaging.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.inAppMessaging.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.inAppMessaging.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
{{- end }}

{{- if .Values.pricingService.enabled }}
{{- if .Values.pricingService.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "commerce-service.fullname" . }}-{{ .Values.pricingService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "commerce-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.pricingService.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "commerce-service.fullname" . }}-{{ .Values.pricingService.name }}
  minReplicas: {{ .Values.pricingService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.pricingService.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.pricingService.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.pricingService.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
{{- end }}

{{- if .Values.conversionTracker.enabled }}
{{- if .Values.conversionTracker.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "commerce-service.fullname" . }}-{{ .Values.conversionTracker.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "commerce-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.conversionTracker.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "commerce-service.fullname" . }}-{{ .Values.conversionTracker.name }}
  minReplicas: {{ .Values.conversionTracker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.conversionTracker.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.conversionTracker.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.conversionTracker.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
{{- end }}
