{{- if .Values.userProfiler.enabled }}
{{- if .Values.userProfiler.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "personalization-service.fullname" . }}-{{ .Values.userProfiler.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "personalization-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.userProfiler.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "personalization-service.fullname" . }}-{{ .Values.userProfiler.name }}
  minReplicas: {{ .Values.userProfiler.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.userProfiler.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.userProfiler.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.userProfiler.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.userProfiler.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.userProfiler.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}

{{- if .Values.recommendationEngine.enabled }}
{{- if .Values.recommendationEngine.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "personalization-service.fullname" . }}-{{ .Values.recommendationEngine.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "personalization-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.recommendationEngine.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "personalization-service.fullname" . }}-{{ .Values.recommendationEngine.name }}
  minReplicas: {{ .Values.recommendationEngine.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.recommendationEngine.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.recommendationEngine.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.recommendationEngine.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.recommendationEngine.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.recommendationEngine.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}

{{- if .Values.personalizationApi.enabled }}
{{- if .Values.personalizationApi.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "personalization-service.fullname" . }}-{{ .Values.personalizationApi.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "personalization-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.personalizationApi.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "personalization-service.fullname" . }}-{{ .Values.personalizationApi.name }}
  minReplicas: {{ .Values.personalizationApi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.personalizationApi.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.personalizationApi.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.personalizationApi.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.personalizationApi.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.personalizationApi.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
